### ISSUE TITLE
Documentation: how to add a permission to a view

### ISSUE THREAD

**Issue by robertlagrant** [ergo/ziggurat_foundations#12]
I'm coming at Pyramid fresh (as in, I haven't learned its vanilla permission system) and I'm struggling to see how to create a view using decorators that is only for a logged in user, or one that is for a logged in user who has a certain permission, and then a certain permission for a certain object.

E.g. Django for case 1:

    @login_required
    def my_view(request):
        ...

Case 2:

    @permission_required('polls.can_vote')
    def my_view(request):
        ...

Case 3 (django-guardian syntax):

    @permission_required_or_403('auth.change_object', (MyObject, 'object', 'object_name'))
    def edit_object(request, object_name):
        ....

I'm sure it's just a docs issue, but can I do the same sort of decorated permissions with ziggurat_foundations?

**Comment by ergo** [comment]
Hello,

On permission system please take a look at:
http://docs.pylonsproject.org/projects/pyramid/en/1.5-branch/narr/security.html#protecting-views-with-permissions

and my tutorial:
http://pyramid-blogr.readthedocs.org/en/latest/authorization.html

It works a bit different in pyramid in general and it can be a concept that is a bit weird for someone just starting with pyramid.

Yes, you use a decorator on your view to specify permission like:
```python
   @view_config(route_name='admin', match_param='action=view_user',
             renderer='json', permission='some_perm')
    def admin_user_view(request):
```

at this point pyramid will know that for this request the CONTEXT object need to supply __acl__ property containing list of entities that have permissions to your page/resource - and then it will be matched with your user object.

So when dealing with URL ROUTING in pyramid you need to specify a context factory:

```python
    config.add_route('some_route', '/some_url', factory='yourapp.security.SomeFactory')
```

https://ziggurat-foundations.readthedocs.org/en/latest/tutorial.html#pyramid-based-examples-of-permission-system-building  - like in this example.

The factory goal is to supply something like 
```python
self.__acl__ = [(Allow, Authenticated, u'view'), (Allow, 'robertlagrant', 'some_perm') ],
```

Ziggurat aids you so you don't have to write all the complicated queries to get results from db for different types of relations between users/groups/resources/permissions.

But you still need to create that __acl__ object on your own :-) If you supply context object and log in user then pyramids ACL policy will do its thing and either let you in or keep you out from specific view.

**Comment by ergo** [comment]
(as in, I haven't learned its vanilla permission system) - you need to read the documentation on that.

Like i mentioned above you just need to pass permission='view' to your `@view_config` decorator, and then provide a context factory that will return an `__acl__` with "view" perm for authenticated users (see example from previous comment).

Try reading my tutorial and follow it - initially it didn't "click" right in my brain when i was starting but it is not a difficult concept :-) It just sounds scary at start.

**Comment by robertlagrant** [comment]
Thanks very much for the quick and thorough response. I had to read that a few times to get it (as much as I have) :) I'm getting there with the general idea, I think.

Is there any reason why it needs an ACL object when I'm passing in the object, user and permission on the view config?

**Comment by ergo** [comment]
I'm not sure I understand what you mean by 
passing in the object, user and permission on the view config".
In view config you should only pass the permission name,
the __ACL__ object will supply user/permission pairs for specific context for this request, and pyramid policy will supply currently logged user and check if user matches one of the values in __ACL__ and in turn if one of those matched objects contain permission that this specific view requires.

**Comment by robertlagrant** [comment]
Sorry, I phrased that badly. I mean the user and object are already known, and I'm passing the permission. I think I'm still coming to grips with how everything fits together; will keep reading.

**Comment by ergo** [comment]
ok, a view permission for objectA is different than permission for object/page B - think of forum moderator permissions - everything would be handled by same view.

So basicly your view tells what permission is needed, you supply user right?
And the missing piece of information is context object with __acl__ that says user robert can view this.

**Comment by ergo** [comment]
@robertlagrant can we close this ticket now? :-)

**Comment by robertlagrant** [comment]
Sure :) Thanks for the advice.
