### ISSUE TITLE
Inconsistency in the documentation - "login" vs. "username"

### ISSUE THREAD

**Issue by peletiah** [ergo/ziggurat_foundations#29]
In the documentation you are using "username" in the configuration but "login" in the example-template. As a new user who hasn't fully grasped the concept it took me a while to figure out that this is the cause why my login fails. 
It's obvious after the fact, but only after some clumsy debugging and sifting through [ziggurat_foundations.ext.pyramid.sign_in](https://github.com/ergo/ziggurat_foundations/blob/master/ziggurat_foundations/ext/pyramid/sign_in.py) I realized my stupid mistake. 
Maybe you could homogenize that in the docs?

And rather than just routing you to ZigguratSignInBadAuth wouldn't it be nicer if an error was thrown that the respective login-keyword could not be found in the request-body?

**Comment by ergo** [comment]
Hi @peletiah,

Sorry about that - I changed the name of the key in configuration to "login" this I think should solve the issue I think?

Thanks for the report.

**Comment by peletiah** [comment]
Thanks!
