### ISSUE TITLE
decrease identifiers

### ISSUE THREAD

**Issue by sahama** [ergo/ziggurat_foundations#51]
In oracleDB names must be from 1 to 30 bytes long. 
may you decrease names to be less than 30? if you do this it is possible to use ziggurat_foundations with oracleDB.

**Comment by ergo** [comment]
Hi, can you be more specific which identifiers you have in mind?

**Comment by sahama** [comment]
Hi.

**Comment by sahama** [comment]
Hi, at first table name `alembic_ziggurat_foundations_version` with length 36. after i rename it to some thing like `alembic_zigg_version`. other errors happened. next i see this:
```
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00972: identifier is too long
 [SQL: '\nCREATE TABLE groups_permissions (\n\tgroup_name NVARCHAR2(50) NOT NULL, \n\tperm_name NVARCHAR2(30) NOT NULL, \n\tCONSTRAINT pk_groups_permissions PRIMARY KEY (group_name, perm_name), \n\tCONSTRAINT fk_groups_permissions_group_name_groups FOREIGN KEY(group_name) REFERENCES groups (group_name) ON DELETE CASCADE\n)\n\n']
 
```

that refer to `fk_groups_permissions_group_name_groups` as column name is too long.
Thanks for taking the time to read this.

**Comment by ergo** [comment]
The project has many long index and table names - I think at this point there is no reasonable way to fix this without breaking backwards compatibility.
Is there a config option for oracle that you can use to make table/index names longer?
Alternatively I would suggest using postgresql as your database option.

**Comment by sahama** [comment]
I searched but i don found any solution to increase it in oracle.
This is may be only solution that i use alternative DBMS.

**Comment by ergo** [comment]
Yes, I think at this point there is little I can do without bad breakage.
I suggest you go with postgresql - since optional nested tree module currently supports only this RDBMS.
