### ISSUE TITLE
Facing issue in Ziggurat foundation migration on MySQL 8.x

### ISSUE THREAD

**Issue by ghost** [ergo/ziggurat_foundations#62]
We are using ziggurat foundation (version 0.7.3) in our project for users, groups maintenance. 

So when we do the setup for the first time for any developer we run the Ziggurat foundation migration script. We recently noticed that for a given user on MySQL 8.x we are facing this error 

Note : One more data point this migration works fine on MySQL 5.x. 

At the migration step '4c10d97c509' we get following error sqlalchemy.exc.ProgrammingError: (_mysql_exceptions.ProgrammingError) (1064, “You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ‘groups where groups.group_name=groups_permissions.group_name)’ at line 2”) [SQL: u’update groups_permissions set group_id = \n    (select id from groups where groups.group_name=groups_permissions.group_name)’] (Background on this error at: http://sqlalche.me/e/f405).

**Comment by ergo** [comment]
Hi,
I will try to set up newer travis config with multiple DB versions so we can spot problems earlier.

**Comment by vinay-is** [comment]
Thanks @ergo and will let you know if face any further issues.......

**Comment by ergo** [comment]
Ok, please update this issue to confirm the issue is fixed, in my 8.x tests every migration passes if you use `master` branch.
