### ISSUE TITLE
Ziggurat-foundations 0.8.2 is not working with pyramid version 1.10.2

### ISSUE THREAD

**Issue by vinay-is** [ergo/ziggurat_foundations#66]
I have the following code in my __init__.py 
config.include('ziggurat_foundations.ext.pyramid.get_user') 

This line fails in Pyramid version 1.10.2 and get the following error 'AttributeError: set_request_property' and I think we need to change the file `get_user.py` line #47 from -
 config.set_request_property(get_user, "user", reify=True)
To
 config.add_request_method(get_user, "user", reify=True)

**Comment by ergo** [comment]
Hey @vinay-is - version 0.8.3  https://pypi.org/project/ziggurat-foundations/0.8.3/ should have that fixed already.

**Comment by vinay-is** [comment]
Great !!!! This was very quick :-) 👍
