### ISSUE TITLE
Warning "all => service" but no service available

### ISSUE THREAD

**Issue by fmigneault** [ergo/ziggurat_foundations#67]
When calling `BaseModel.all()`, we receive a deprecation warning asking to use the corresponding `service`, but many model types don't have such service. 
I'm thinking about `UserGroupMixin` for instance, but there could be other.
Other services should be implemented, or adjust the warning accordingly.

**Comment by ergo** [comment]
Hey, BaseService has `all()` method.

**Comment by fmigneault** [comment]
Great! Thanks
