### ISSUE TITLE
New version for SQLAlchemy 2.0

### ISSUE THREAD

**Issue by fmigneault** [ergo/ziggurat_foundations#74]
Hi @ergo, 

Enabling `SQLALCHEMY_WARN_20=1` in preparation of updating it, I encountered the warnings already fixed by #72.
Will a new version be released soon to pin it in requirements? 

Thanks

**Comment by marcin-lulek-cint** [comment]
Hey, I don't think I should pin the requirements on my end if I can avoid it - you can easily pin it with your own requirements/lock file.
It would be great to fix errors if they happen in 2.x.

**Comment by ergo** [comment]
Hey, I don't think I should pin the requirements on my end if I can avoid it - you can easily pin it with your own requirements/lock file.
It would be great to fix errors if they happen in 2.x.

**Comment by fmigneault** [comment]
Sorry I wasn't clear. I mean to pin `ziggurat_foundations` to have the latest commits since 0.8.4. I'm not expecting it to pin `sqlalchemy`.

**Comment by ergo** [comment]
Ok, sure I will make a new release soon for you.

**Comment by fmigneault** [comment]
@ergo Hi Ergo, just a quick reminder. The new release is still not available. Is this planned for later changes? Thanks

**Comment by ergo** [comment]
Sorry, I've made a release right now. Thanks for the reminder
